server:
  port: 10092
  context-path: /client2

security:
  oauth2:
    client:
      client-id: clientId2
      client-secret: clientSecrect2
      user-authorization-uri: http://127.0.0.1:10082/server/oauth/authorize
      access-token-uri: http://127.0.0.1:10082/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:10082/server/oauth/token_key