server:
  port: 10081
  session:
    #session过期时间秒,spring session的最短过期时间为1分
    timeout: 600

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.141.128:3306/demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
#    username: jeff
#    password: 123456
    url: jdbc:mysql://47.94.138.114:3306/demo?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    username: root
    password: jeff@2018!@#


  # redis配置
  redis:
    host: 47.94.138.114
    port: 6379
    password: jeff@2018!

  #session配置
  session:
    store-type: redis

#security配置，默认开启
security:
  basic:
    enabled: true
  oauth2:
    client:
      client-id: appid
      client-secret: appSecret

#### 自定义登录页
jeff:
  security:
    browser:
      signUpUrl: /demo-signup.html
#      login-page: /demo-signIn.html
      #登录成功或失败后的处理
#      login-type: JSON
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*
    social:
      filter-processes-url: /qqLogin
      qq:
        app-id: 1109751379
        app-secret: r1AqvVa9HelLFVUL
        provider-id: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4

